name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build -t url-shortener-app .

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image to Docker Hub
      run: |
        docker tag url-shortener-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/url-shortener:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/url-shortener:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker stop fastapi || true
          docker rm fastapi || true
          docker pull ${{ secrets.DOCKER_USERNAME }}/url-shortener:latest
          sudo docker run -d --name fastapi -p 80:8000  ${{ secrets.DOCKERHUB_USERNAME }}/url-shortener:latest
