name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build -t url-shortener-app .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: |
        docker tag url-shortener-app:latest sporkygg/url-shortener:latest
        docker push sporkygg/url-shortener:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker stop `docker ps -q` || true
          docker rm `docker ps -aq` || true
          docker pull ${{ secrets.DOCKER_USERNAME }}/url-shortener:latest
          sudo docker run -d -p 80:8000  ${{ secrets.DOCKER_USERNAME }}/url-shortener:latest
