name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image to Docker Hub
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        docker build --build-arg AWS_ACCESS_KEY_ID --build-arg AWS_SECRET_ACCESS_KEY -t url-shortener-app .
        docker tag url-shortener-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/url-shortener:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/url-shortener:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker stop fastapi || true
          docker rm fastapi || true
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/url-shortener:latest
          sudo docker run -d --name fastapi -p 8000:8000  ${{ secrets.DOCKERHUB_USERNAME }}/url-shortener:latest
